name: backend-test
defaults:
    run:
        working-directory: ./backend
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup AtlasCLI
              uses: ariga/setup-atlas@v1

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install go packages
              run: go mod download

            - name: Run tests
              run: make run-all-tests
